<footer>
  <div class="inner cont flex column">
    <div id="footer-bi-logo-w" ><img alt="EESPACIO I（エスパシオ ワン）" src="assets/img/bi/espacioone_bi_logo_w.svg" loading="lazy"></div>
    <ul class="flex foot-nav">
      <li class="menu"><a href="#fv" class="scrl">Top</a></li>
      <li class="menu"><a href="#news" class="scrl">News</a></li>
      <li class="menu"><a href="#about" class="scrl">About ESPACIO</a></li>
      <li class="menu"><a href="#service" class="scrl">Our Service</a></li>
      <li class="menu"><a>Cruising</a></li>
      <li class="menu"><a>Wedding</a></li>
      <li class="menu"><a href="#facility" class="scrl">Facility</a></li>
      <li class="menu"><a href="#contact" class="scrl">Contact Us</a></li>
    </ul>
    <ul class="flex foot-links">
      <li class="menu"><a href="https://www.okinawa-watabewedding.co.jp/company/" target="_blank">会社概要<span class="material-icons">open_in_new</span></a></li>
      <li class="menu"><a href="https://www.okinawa-watabewedding.co.jp/privacy/" target="_blank">プライバシーポリシー<span class="material-icons">open_in_new</span></a></li>
      <li class="menu"><a href="https://www.okinawa-watabewedding.co.jp/gdpr_privacy" target="_blank">GDPRプライバシーポリシー<span class="material-icons">open_in_new</span></a></li>
      <li class="menu"><a href="https://www.instagram.com/espacio.cruising.okinawa/" target="_blank">Instagram<span class="material-icons">open_in_new</span></a></li>
    </ul>
    <div class="copyrights">Copyright © 2023 ESPACIO All Rights Reserved.</div>
  </div>
</footer>
